---
title: "Data Application"
author: "Yenny Webb-Vargas"
date: "Wednesday, February 04, 2015"
output: html_document
---

```{r}
source('~/GitHub/functional_mediation/sff_vec2list.R')
source('~/GitHub/functional_mediation/lplot.R')

source('~/GitHub/functional_mediation/sfs_Mediation.R')  
source('~/GitHub/functional_mediation/est_se_fgam.R')  
```


```{r, cache=TRUE}
library(R.matlab)
meta_file = '~/GitHub/functional_mediation/data_application/meta.mat'

meta = readMat(meta_file, fixNames=TRUE)[['meta']]
```

```{r}
list_names = 'heat_crating: {1x93 cell}
         soundpain_crating: {1x93 cell}
              iads_crating: {1x93 cell}
          heat_orating_int: {1x93 cell}
          heat_orating_unp: {1x93 cell}
     soundpain_orating_int: {1x93 cell}
     sounpdain_orating_unp: {1x93 cell}
          iads_orating_int: {1x93 cell}
          iads_orating_unp: {1x93 cell}
                       run: {1x93 cell}
                     trial: {1x93 cell}
                 condition: {1x93 cell}
                  iads_set: {1x93 cell}
                heat_level: {1x93 cell}
         heat_crating_peak: {1x93 cell}
           soundpain_level: {1x93 cell}
    soundpain_crating_peak: {1x93 cell}
                iads_level: {1x93 cell}
         iads_crating_peak: {1x93 cell}
                  subjects: {1x93 cell}
                   ratings: {1x93 cell}
                      temp: {1x93 cell}'

list_names = gsub(' {1x93 cell}\n', '', list_names, fixed=TRUE)
list_names = gsub(' {1x93 cell}', '', list_names, fixed=TRUE)
list_names = strsplit(list_names, ":")[[1]]
list_names = sapply(list_names, function(x) gsub(' ', '', x))

names(meta) = list_names
```


```{r}
get_data0 <- function(subj){
  M  = meta[["heat_crating"]][[subj]][[1]][1:36,]
  Yt = meta[["ratings"]][[subj]][[1]]
  X  = meta[["heat_level"]][[subj]][[1]][1:36]
  
  colnames(M) = paste0('M',1:ncol(M))
  
  Y = rep(NA, 36)
  Y[1:length(Yt)] = Yt # Assuming the observed values represent the first trials
  
  n_miss = 36 - length(Yt)
  
  dta = data.frame(ID = subj,ID2=1:length(X), n_miss = n_miss, X, Y, M)
  return(dta)
}
```

```{r}
big_dta0 = get_data0(1)
for(i in 2:93) big_dta0 = rbind(big_dta0, get_data0(i)) 
apply(big_dta0,2,function(x) sum(is.na(x)))
```

There are 131 observations missing Y, and by time point 187, there are many more NaNs.


Dropping all cases with missing mediator, missing outcome, and subsetting to 186 time points:

```{r}
get_data <- function(subj){
  M  = meta[["heat_crating"]][[subj]][[1]][1:36,1:186]
  Yt = meta[["ratings"]][[subj]][[1]]
  X  = meta[["heat_level"]][[subj]][[1]][1:36]
  
  colnames(M) = paste0('M',1:ncol(M))
  
  Y = rep(NA, 36)
  Y[1:length(Yt)] = Yt # Assuming the observed values represent the first trials
  
  cc = complete.cases(cbind(X,Y,M))
  
  n_miss = sum(cc)
  
  dta = data.frame(ID = subj, ID2=1:length(X), n_miss = n_miss, X, Y, M)[cc,]
  return(dta)
}
```

```{r}
big_dta = get_data(1)
for(i in 2:93) big_dta = rbind(big_dta, get_data(i)) 
apply(big_dta,2,function(x) sum(is.na(x)))
apply(big_dta,1,function(x) sum(is.na(x)))
```

# Plots!

Following [this post](https://learnr.wordpress.com/2010/01/26/ggplot2-quick-heatmap-plotting/)

```{r}
library(ggplot2)
library(reshape2)
library(plyr)

big_dta0.m <- melt(big_dta0, id=c("ID","ID2", "n_miss", "X", "Y"), value.name="value")

big_dta0.m$ID3 = with(big_dta0.m, paste0(ID,ID2))
```


# Unscaled data
```{r}
p <- ggplot(big_dta0.m, aes(variable, ID3)) + geom_tile(aes(fill = value), colour = "white") + scale_fill_gradient(low = "white", high = "steelblue")
base_size <- 9
p <- p + theme_grey(base_size = base_size) + labs(x = "", y = "") + scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) + theme(legend.position = "none", axis.ticks = element_blank(), axis.text.x = element_text(size = base_size * 0.8, angle = 330, hjust = 0, colour = "grey50"))
```

```{r, fig.height=9,fig.width=3.5,dpi=200, eval=FALSE}
p
```


```{r,fig.height=9,fig.width=7,dpi=100}
all_M = big_dta0[,grep("M", colnames(big_dta0))]
image(t(all_M))
```

