---
title: "Results from Simulation. No noise"
author: "Yenny Webb-Vargas"
date: "Thursday, November 13, 2014"
output: html_document
---


```{r}
mydir = "~/GitHub/functional_mediation/Simulations/Model_based_Simulation/gypsie/"
```

# Results from simulation 1
```{r, echo=FALSE}
load(paste0(mydir,dir(mydir)[grep("Simulation_1_nonoise", dir(mydir))]))
matplot(t(A), col = rgb(200,1,1, 30, maxColorValue = 255), type="l", main="Alpha")
matplot(t(B), col = rgb(200,1,1, 30, maxColorValue = 255), type="l", main="Beta")
matplot(t(B*A), col = rgb(200,1,1, 30, maxColorValue = 255), type="l", main="Alpha*Beta")
matplot(t(Pall), col = rgb(200,1,1, 30, maxColorValue = 255), type="l", main="P-value 1")
matplot(t(Pall2), col = rgb(200,1,1, 30, maxColorValue = 255), type="l", main="P-value 1")
```

# Results from simulation 2
```{r, echo=FALSE}
load(paste0(mydir,dir(mydir)[grep("Simulation_2_nonoise", dir(mydir))]))
matplot(t(A), col = rgb(1,200,1, 30, maxColorValue = 255), type="l", main="Alpha")
matplot(t(B), col = rgb(1,200,1, 30, maxColorValue = 255), type="l", main="Beta")
matplot(t(B*A), col = rgb(1,200,1, 30, maxColorValue = 255), type="l", main="Alpha*Beta")
matplot(t(Pall), col = rgb(1,200,1, 30, maxColorValue = 255), type="l", main="P-value 1")
matplot(t(Pall2), col = rgb(1,200,1, 30, maxColorValue = 255), type="l", main="P-value 2")
```

# Results from simulation 3
```{r, echo=FALSE}
load(paste0(mydir,dir(mydir)[grep("Simulation_3_nonoise", dir(mydir))]))
matplot(t(A), col = rgb(200,200,1, 30, maxColorValue = 255), type="l", main="Alpha")
matplot(t(B), col = rgb(200,200,1, 30, maxColorValue = 255), type="l", main="Beta")
matplot(t(B*A), col = rgb(200,200,1, 30, maxColorValue = 255), type="l", main="Alpha*Beta")
matplot(t(Pall), col = rgb(200,200,1, 30, maxColorValue = 255), type="l", main="P-value 1")
matplot(t(Pall2), col = rgb(200,200,1, 30, maxColorValue = 255), type="l", main="P-value 2")
```

# Results from simulation 4
```{r, echo=FALSE}
load(paste0(mydir,dir(mydir)[grep("Simulation_4_nonoise", dir(mydir))]))
matplot(t(A), col = rgb(100,100,200, 30, maxColorValue = 255), type="l", main="Alpha")
matplot(t(B), col = rgb(100,100,200, 30, maxColorValue = 255), type="l", main="Beta")
matplot(t(B*A), col = rgb(100,100,200, 30, maxColorValue = 255), type="l", main="Alpha*Beta")
matplot(t(Pall), col = rgb(100,100,200, 30, maxColorValue = 255), type="l", main="P-value 1")
matplot(t(Pall2), col = rgb(100,100,200, 30, maxColorValue = 255), type="l", main="P-value 2")
```
